name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"  # Specify your desired Terraform version

      # Step 3: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:

          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1  # Ensure AWS_REGION is set in Secrets

      # Step 4: Initialize Terraform (downloads plugins, sets up backend)
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate the Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan (Generate execution plan to review changes)
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Apply Terraform configuration (provision resources)
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Automatically approve and apply changes
